# Generated by Django 2.2.16 on 2021-11-13 14:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0002_auto_20211113_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.PositiveSmallIntegerField(help_text='Год издания', validators=[django.core.validators.MaxValueValidator(2021)], verbose_name='Год'),
        ),
    ]
